[package]
name = "transfer-token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.16.8"
solana-sdk = "1.16.8"
